# Groupby for bar charts

## Load data

In [36]:
path = '../../data/EIA/fuel_type_data_california.parquet'

In [37]:
import pandas as pd
df = pd.read_parquet(path)

df

,period,respondent,respondent-name,fueltype,type-name,value,value-units
0,2025-04-22 20:00:00-07:00,CAL,California,BAT,Battery storage,179,megawatthours
1,2025-04-22 20:00:00-07:00,CAL,California,COL,Coal,216,megawatthours
...,...,...,...,...,...,...,...
452546,2018-12-31 17:00:00-07:00,CAL,California,WAT,Hydro,2880,megawatthours
452547,2018-12-31 17:00:00-07:00,CAL,California,WND,Wind,2628,megawatthours

In [38]:
df.columns

Index(['period', 'respondent', 'respondent-name', 'fueltype', 'type-name',
       'value', 'value-units'],
      dtype='object')

In [39]:
df = df.set_index('period').sort_index()
df = df.loc['2024', ['type-name', 'value']]
df.columns = ['technology','energy']
df

                          technology  energy
period
2024-01-01 00:00:00-07:00       Wind     243
2024-01-01 00:00:00-07:00      Hydro    3541
...                              ...     ...
2024-12-31 23:00:00-07:00      Hydro    4125
2024-12-31 23:00:00-07:00       Wind     476

[70224 rows x 2 columns]

## Calculate temporal properties

In [55]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), '../..'))
if project_root not in sys.path:
    sys.path.append(project_root)
import modules.utils as utils
df=utils.add_time_features(df)
df

,technology,energy,hour,year,month,day,weekday,weekend
period,,,,,,,,
2024-01-01 00:00:00-07:00,Wind,243,0,2024,1,1,0,False
2024-01-01 00:00:00-07:00,Hydro,3541,0,2024,1,1,0,False
...,...,...,...,...,...,...,...,...
2024-12-31 23:00:00-07:00,Hydro,4125,23,2024,12,31,1,False
2024-12-31 23:00:00-07:00,Wind,476,23,2024,12,31,1,False

In [40]:
df['hour'] = df.index.hour
df

                          technology  energy  hour
period
2024-01-01 00:00:00-07:00       Wind     243     0
2024-01-01 00:00:00-07:00      Hydro    3541     0
...                              ...     ...   ...
2024-12-31 23:00:00-07:00      Hydro    4125    23
2024-12-31 23:00:00-07:00       Wind     476    23

[70224 rows x 3 columns]

## Steps

### Aggregate data with groupby

### Reset index to transform result into a data frame

### Bar chart

## Different parameters to visualize the bar chart

### Aggregate by 3 categorical columns

### Plot with facets

#### Columns

#### Rows

### Aggregate by 4 categorical columns